#ifndef STYLE_H
#define STYLE_H

#define VIEWPORT_HEIGHT (800)
#define VIEWPORT_WIDTH (800)
#define SIDEBAR_WIDTH (VIEWPORT_WIDTH / 2)

#define BORDER_SIZE (2)
#define ANCHOR_SIZE (10)

#define SLIDER_HEIGHT (VIEWPORT_HEIGHT / 10)
#define SLIDER_WIDTH (SLIDER_HEIGHT / 2)
#define SLIDER_FONT_SIZE (SLIDER_HEIGHT / 5)

#define MISC_BUTTON_HEIGHT (VIEWPORT_HEIGHT / 20)
#define LAYER_BUTTON_HEIGHT (VIEWPORT_HEIGHT / 12)
#define FILTER_SELECT_HEIGHT (VIEWPORT_HEIGHT / 25)

#define MAX_LAYERS (4)
#define CURRENT_LAYER_COLOR ("#BABABA")

#endif
